sensorcommands: avoid stringop-truncation warning
When compiling ipmi-fru-parser with GCC 13.2.0, I observed the
following:

```
../subprojects/phosphor-host-ipmid/dbus-sdr/sensorcommands.cpp:1748:17: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 16 equals destination size [-Werror=stringop-truncation]
 1748 |     std::strncpy(record.body.id_string, name.c_str(),
 ```

Switch to a memcpy instead of a strncpy to avoid the warning.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I43d5cddd74cf1ad2d686e9529e87ec416e2bb6a0