Fix host-interface.hpp build error
Repo CI gives below error:
```
../host-interface.hpp:53:23: error: private field 'bus' is not used [-Werror,-Wunused-private-field]
   53 |     sdbusplus::bus_t& bus;
```

Fix it by removing the unused field.

Change-Id: Idf2c4c2581e79809397cc7327472061432ad9aff
Signed-off-by: Lei YU <yulei.sh@bytedance.com>