clang-tidy: Suppress unused lambda captures
The following errors were reported during clang-tidy enablement due
to unused lambda captures. This temporary fix suppresses the warnings
using pragma diagnostic ignore checks until a permanent solution is
implemented.

Added pragma directives to suppress the -Wunused-lambda-capture
warning in specific code sections.

'''
/ipmid-new.cpp:399:11: error: lambda capture 'io' is not used [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: If6113441c905cf782f26798d0e856521bd546f90
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>