storagehandler: fix compile without open-power
When the `open-power` meson option is disabled, the code fails with
the following compile failure:

```
../storagehandler.cpp: In function ‘ipmi::RspType<short unsigned int> ipmiStorageAddSEL(uint16_t, uint8_t, uint32_t, uint16_t, uint8_t, uint8_t, uint8_t, uint8_t, std::array<unsigned char, 3>)’:
../storagehandler.cpp:685:27: error: unused variable ‘procedureType’ [-Werror=unused-variable]
  685 |     static constexpr auto procedureType = 0xDE;
      |                           ^~~~~~~~~~~~~
../storagehandler.cpp:677:64: error: unused parameter ‘sensorType’ [-Werror=unused-parameter]
  677 |                       [[maybe_unused]] uint8_t evmRev, uint8_t sensorType,
```

Add trivial changes to fix.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ia7cc8dab700381c78461899bfc8c33d43cab3625