Fix include path for message.hpp
This resolves the below compilation error related to the missing
message.hpp file during full build.

'''
usr/include/ipmid/message/pack.hpp:18:10: fatal error: include/ipmid/message.hpp:
No such file or directory
'''

Updated the include directive to use the correct relative path for
message.hpp

Change-Id: Ice8a60a7030448ce75f0fa255ded9117beb1a71f
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>