user: Fix the password map don't match the shadow
Currently, the password map update relies on the file modified
timestamp (stat). In most scenarios, BMC, as an embedded device, uses
the jffs2 file system. However, jffs2 stores timestamps in a 32-bit
format with second precision.

If the `setUserName` and `setUserPassword` commands are completed within
1 second, it will cause the second set of data not to be updated in the
map, resulting in inconsistency between the password map and the storage
in the shadow file.

This patch adds a file watch mechanism to monitor the file changes and
set the file last updated time to initial value when the file changes.

Tested:
1. Before this patch, set the user name and password quickly, use the
new user name and password to login, and the login failed.
```
~# ipmitool -I lanplus -H $bmc -U $username_old -P '$password_old' user set name 2 $username_new
~# ipmitool -I lanplus -H $bmc -U $username_new -P '$password_old' user set password 2 $password_new

~# ipmitool -I lanplus -H $bmc -U $username_new -P '$password_new' mc info
Error: Unable to establish IPMI v2 / RMCP+ session
```

2. After this patch, set the user name and password quickly, test pass
in a long time.
```
while true; do
ipmitool -I lanplus -H $bmc -U $username_old -P '$password_old' user set name 2 $username_new
ipmitool -I lanplus -H $bmc -U $username_new -P '$password_old' user set password 2 $password_new

ipmitool -I lanplus -H $bmc -U $username_new -P '$password_new' mc info

sleep 1

ipmitool -I lanplus -H $bmc -U $username_new -P '$password_new' user set name 2 $username_old
ipmitool -I lanplus -H $bmc -U $username_old -P '$password_new' user set password 2 $password_old

ipmitool -I lanplus -H $bmc -U $username_old -P '$password_old' mc info
done
```

Change-Id: I537f6d55993b72981b1f0f2dc661bcc35d7c1cd1
Signed-off-by: Jian Zhang <zhangjian.3032@bytedance.com>