Remove HMAC-SHA1 from Authentication/Integrity Alg
Reason: For security reason- HMAC-SHA1 is deprecated.

Plesae note: Use latest ipmitool or ipmitool v1.8.18.177.g7ccea28 later

Tested :
ipmitool -H <BMCIP>  -I lanplus -U <username> -P <password> -C 3  raw 6 1
Error in open session response message : invalid authentication algorithm
Error: Unable to establish IPMI v2 / RMCP+ session

ipmitool -H <BMCIP> -I lanplus -U <username> -P <password> -C 17 raw 6 1
 23 00 00 40 02 bf 57 01 00 91 00 0d 62 04 f5

Signed-off-by: Suryakanth Sekar <suryakanth.sekar@linux.intel.com>
Change-Id: I8226c06a248ec601d848c1e2dd7eb129a272c503