clang-tidy: Fix braces warning
The following error was reported during clang-tidy enablement due to
the initialization of a subobject without braces in apphandler.cpp.
This fix addresses the issue by modifying the initialization to
include braces around each subobject.

'''
apphandler.cpp:653:31: error: suggest braces around initialization of subobject [-Werror]
'''

Tested: Build and unit testing verified.

Change-Id: Icfe58be0ff65ae17fc8f6a7c1f5ac06aedbb1e61
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>