clang-tidy: Fix packed member address warning
The following error was reported during clang-tidy enablement due to
taking the address of a packed member

'''
../apphandler.cpp:637:31:
  error: taking address of packed member 'recordID' of class or structure 'ipmi::sel::SELEventRecord' may result in an unaligned pointer value [-Werror]
'''

Fix is to Copy the packed member to a temporary variable before using
its address. This ensures proper alignment.

Tested: Build and unit testing verified.

Change-Id: Ib547c1764ec4402a18851b8130f06e60cb66dae3
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>