clang-tidy: Fix Dangling Pointer Warning
The following error was reported during clang-tidy enablement due to
a temporary object being destroyed at the end of the full-expression,
leaving a dangling pointer. This fix addresses the issue by changing
str to a proper string instead of a string_view.

'''
0m../apphandler.cpp:545:36: error: object backing the pointer will be destroyed at the end of the full-expression [-Werror
0m../apphandler.cpp:564:40: error: object backing the pointer will be destroyed at the end of the full-expression [-Werror
1m../apphandler.cpp:523:36: error: object backing the pointer will be destroyed at the end of the full-expression [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: I4f8f2dc3f24a4e417e6805075cfaefddb111efaa
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>