clang-tidy: Remove unused lambda captures
The following errors were reported during clang-tidy enablement due
to unused lambda captures.

'''
/ipmid-new.cpp:399:11: error: lambda capture 'io' is not used [-Werror
'''

The fix involves removing these unused lambda captures.

Tested: Build and unit testing verified.

Change-Id: If6113441c905cf782f26798d0e856521bd546f90
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>