clang-tidy: Fix braces around initialization
The following error was reported during clang-tidy enablement due to
the initialization of a subobject without braces. This fix addresses
the issue by replacing auto by uint32.

'''
apphandler.cpp:637:31: error: suggest braces around initialization of subobject [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: Id8c423ac5831c7045c5903d9a306158b4fddf462
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>